# Generated by Django 4.0.6 on 2022-08-02 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30)),
                ('car_image', models.ImageField(upload_to='car_images')),
                ('car_rent', models.IntegerField(default=None)),
            ],
            options={
                'ordering': ['car_name'],
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
                ('city_image', models.ImageField(upload_to='city_images')),
                ('city_summary', models.CharField(max_length=200)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=None)),
                ('offer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=40)),
                ('place_intro', models.TextField(default=None)),
                ('place_images', models.ImageField(upload_to='place_images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.city')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
    ]
