# Generated by Django 4.0.6 on 2022-08-02 03:43

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_color',
            field=colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF'], default=0),
        ),
    ]
